//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace calypso_app.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class proveedor
    {
        public int id_proveedor { get; set; }
        public string rfc_proveedor { get; set; }
        public string razonsocial_proveedor { get; set; }
        public int id_usuario { get; set; }
    
        public virtual usuario usuario { get; set; }
    }
}
